name: Build Bubblewrap TWA APK / AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Make Gradle executable
        run: |
          chmod +x twa/gradlew

      - name: Build Bubblewrap TWA APK (debug)
        run: |
          cd twa
          ./gradlew :app:assembleDebug

      - name: Build Bubblewrap TWA AAB (debug)
        run: |
          cd twa
          ./gradlew :app:bundleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TCRadios-debug-apk
          path: twa/app/build/outputs/apk/debug/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: TCRadios-debug-aab
          path: twa/app/build/outputs/bundle/debug/*.aab
